### ISSUE TITLE
build vk_video_encoder fail (multiple rules generate)

### ISSUE THREAD

**Issue by Carter-chao** [nvpro-samples/vk_video_samples#106]
I installed the environment dependencies according to the instructions in build.md and successfully ran the update_external_sources.sh script.
Manually or using vscode + cmake-tools, building vk_video_decoder works without any issues.
Manually building vk_video_encoder works without any issues,
but when trying to build vk_video_encoder using vscode + cmake-tools, I get the following error: CMake Error:
Running

'/usr/local/bin/ninja' '-C' '/home/user/vk_video_samples/vk_video_encoder/vsbuild' '-t' 'recompact'

failed with:

ninja: error: build.ninja:2158: multiple rules generate /home/user/vk_video_samples/common/libs/VkCodecUtils/HelpersDispatchTable.cpp

The build command generated by Visual Studio Code is:
/usr/bin/cmake -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++ --no-warn-unused-cli -S/home/user/vk_video_samples/vk_video_encoder -B/home/user/vk_video_samples/vk_video_encoder/vsbuild -G Ninja

**Comment by Carter-chao** [comment]
Great! It's working normally now.

**Comment by dabrain34** [comment]
#107 has been merged, this issue can be closed
