### ISSUE TITLE
CmdBeginVideoCodingKHR should be passed all reference slots to be used

### ISSUE THREAD

**Issue by airlied** [nvpro-samples/vk_video_samples#11]
The spec says: for CmdBeginVideoCodingKHR
```
pReferenceSlots is a pointer to an array of VkVideoReferenceSlotKHR structures specifying reference slots, used within the video command context between this vkCmdBeginVideoCodingKHR command and the vkCmdEndVideoCodingKHR commmand that
follows. Each reference slot provides a slot index and the VkVideoPictureResourceKHR
specifying the reference picture resource bound to this slot index. A slot index must not appear
more than once in pReferenceSlots in a given command.
```

For CmdVideoDecodeKHR:
```
pSetupReferenceSlot is a pointer to a VkVideoReferenceSlotKHR structure used for generating a
reconstructed reference slot and Picture Resource. pSetupReferenceSlot->slotIndex specifies the
slot index number to use as a target for producing the Reconstructed (DPB) data.
pSetupReferenceSlot must be one of the entries provided in VkVideoBeginCodingInfoKHR via
the pReferenceSlots within the vkCmdBeginVideoCodingKHR command that established the
Vulkan Video Encode Context for this command.
```

This to me reads that the Begin coding should contain all the slot indexes for used references and generated references.

**Comment by zlatinski** [comment]
> This to me reads that the Begin coding should contain all the slot indexes for used references and generated references.

Hi @airlied,
CmdBeginVideoCoding() must contain all DPB image resources and their corresponding slots for the currently used and future generated references by the CmdVideoDecode() commands until CmdEndVideoCoding().
The current version of the application is only recording one  CmdVideoDecode() command per CmdBegin/EndVideoCoding() sequence, so it does require only the DPBs that are going to be used as references or generated by this command in the process of decoding for this one decode frame. The CmdVideoDecode() command does not care about DBP buffers that are going to be generated in the future or DBPs which are not currently used as reference images and so those are not passed in the CmdBeginVideoCoding().

**Comment by zlatinski** [comment]
> This to me reads that the Begin coding should contain all the slot indexes for used references and generated references.

Hi @airlied,
CmdBeginVideoCoding() must contain all DPB image resources and their corresponding slots for the currently used and future generated references by the CmdVideoDecode() commands until CmdEndVideoCoding().
THe current version of the application is only recording one  CmdVideoDecode() command per CmdBegin/EndVideoCoding() sequence, so it does require only the DPBs that are going to be used or generated for this one frame. The CmdVideoDecode() command does not care about DBP buffers that are going to be generated in the future or DBPs which are not currently used as reference images.
