### ISSUE TITLE
 what():  failed to find any capable Vulkan physical device

### ISSUE THREAD

**Issue by bcizmeci** [nvpro-samples/vk_video_samples#16]
When I compile and try to run the test. the GPU is not detected (RTX 3070, cuda 11.4, vulkan version: 1.2.131.2-1)

./vk-video-dec-test -i /home/burak/Downloads/Remote_Cat_2021_ETH_Version.mp4 
Enumerating instance layers:
	VK_LAYER_KHRONOS_validation
	VK_LAYER_LUNARG_standard_validation
Looking for instance layers:
Enumerating instance extensions:
	VK_KHR_device_group_creation
	VK_KHR_display
	VK_KHR_external_fence_capabilities
	VK_KHR_external_memory_capabilities
	VK_KHR_external_semaphore_capabilities
	VK_KHR_get_display_properties2
	VK_KHR_get_physical_device_properties2
	VK_KHR_get_surface_capabilities2
	VK_KHR_surface
	VK_KHR_surface_protected_capabilities
	VK_KHR_xcb_surface
	VK_KHR_xlib_surface
	VK_EXT_acquire_xlib_display
	VK_EXT_debug_report
	VK_EXT_debug_utils
	VK_EXT_direct_mode_display
	VK_EXT_display_surface_counter
Looking for instance extensions:
	VK_KHR_surface
	VK_KHR_xcb_surface
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to find any capable Vulkan physical device
Aborted (core dumped)

**Comment by kwizart** [comment]
I'm reproducing the same issue with the vulkan beta driver (on Fedora 36 with GM107GL).

modinfo -F version nvidia
515.49.15

Here is the vulkaninfo ouput https://paste.centos.org/view/3e342545

Is the hardware is missing any required feature to function ? (for at least, to decode h264 ?)

Thanks.

**Comment by kwizart** [comment]
Okay worth retesting later according to
https://github.com/nvpro-samples/vk_video_samples/issues/18#issuecomment-1248192770
