### ISSUE TITLE
VK_ERROR_INITIALIZATION_FAILED calling vkGetPhysicalDeviceVideoCapabilitiesKHR

### ISSUE THREAD

**Issue by vtchek-unity** [nvpro-samples/vk_video_samples#23]
Hello, running the sample I get unresolved external symbols (the functions related to the video api) 
<img width="1413" alt="Screenshot 2022-10-13 135038" src="https://user-images.githubusercontent.com/90194235/195588957-c260a8af-f632-4cb1-82ce-4653315535e6.png">
**Driver Info:**
<img width="397" alt="driverinfo" src="https://user-images.githubusercontent.com/90194235/195596469-6fd68499-a685-46e5-ad56-b9d33ead1c90.png">
**Lib dump:**
The functions doesn't seem to be present in the lib
[vulkandumplib.txt](https://github.com/nvpro-samples/vk_video_samples/files/9776635/vulkandumplib.txt)

EDIT : I used the `DispatchLoaderDynamic` to load the function addresses, but I get this error : 
<img width="913" alt="error" src="https://user-images.githubusercontent.com/90194235/195602827-f564d3be-1dea-4fe0-b3de-96f485dbedcf.png">

I'm using the latest Vulkan SDK version.

Is it related to the driver?

**Comment by zlatinski** [comment]
The standard vulkan-1.lib loader should not have the video symbols, since the spec is not officially released yet.
For the dynamic loader, are you sure you are using the NVIDIA's physical device GPU instance?
Can you pleases provide the output dump of vulkaninfo?

**Comment by vtchek-unity** [comment]
**vulkaninfoSDK dump:** 
[vulkaninfodump.txt](https://github.com/nvpro-samples/vk_video_samples/files/9798762/vulkaninfodump.txt)
My app is picking the Nvidia device as we can see on the screenshot: 
<img width="517" alt="pickeddevice" src="https://user-images.githubusercontent.com/90194235/196137694-6788a783-a95b-4853-93c8-21d806b3aabf.png">
Also calling `vkCreateVideoSessionKHR` I get a `eErrorIncompatibleDriver`

**Comment by vtchek-unity** [comment]
**Logs of vulkaninfo:**
[vulkaninfodump.txt](https://github.com/nvpro-samples/vk_video_samples/files/9798939/vulkaninfodump.txt)
**Logs of the encoder sample:** 
[log_nvprosample.txt](https://github.com/nvpro-samples/vk_video_samples/files/9798940/log_nvprosample.txt)
<img width="644" alt="dl" src="https://user-images.githubusercontent.com/90194235/196142628-319a838a-d7be-4708-9406-ff44539b1a4c.png">

**Comment by zlatinski** [comment]
> Vulkan Instance Version: **1.3.224**
> Instance Extensions: count = 17

The driver should at least  support 1.3.229 for this latest version of the application.
In addition, your version of the driver does not support any video extensions:
	VK_EXT_video_encode_h264                  : extension revision 9
	VK_EXT_video_decode_h264                  : extension revision 8
	VK_EXT_video_decode_h265                  : extension revision 6
	VK_KHR_video_decode_queue                 : extension revision 7
	VK_KHR_video_encode_queue                 : extension revision 7
	VK_KHR_video_queue                        : extension revision 8
	VK_NV_video_queue                         : extension revision 1

Please download and install the latest Vulkan BETA drivers from https://developer.nvidia.com/vulkan-driver

**Comment by vtchek-unity** [comment]
I can't find anywhere the 1.3.229 version of the Vulkan SDK, I've downloaded the latest version available on the website : [https://vulkan.lunarg.com/sdk/home#windows] which is 1.3.224

I've already dowloaded the latest BETA Drivers as we can see in the vulkaninfodump.txt :
<img width="328" alt="driver_version" src="https://user-images.githubusercontent.com/90194235/196379913-0b902a0b-159d-4c93-86ee-327c70255480.png">
[NVIDIA System Information 10-18-2022 10-06-05.txt](https://github.com/nvpro-samples/vk_video_samples/files/9808478/NVIDIA.System.Information.10-18-2022.10-06-05.txt)

**In the vulkaninfodump I posted:** 
`Device Extensions: count = 182
...
VK_EXT_video_encode_h264                    : extension revision 9
VK_EXT_video_decode_h264                    : extension revision 7
VK_EXT_video_decode_h265                    : extension revision 5
VK_KHR_video_decode_queue                 : extension revision 6
VK_KHR_video_encode_queue                 : extension revision 7
`
`VK_NV_video_queue : extension revision 1` is not listed in the vulkansdkinfodump.

I don't know what I'm missing...

**Comment by zlatinski** [comment]
Hi [vtchek-unity](https://github.com/vtchek-unity). 1.3.224 should be fine. VK_NV_video_queue is not important.
We are double checking the latest BETA release driver against the encoder sample and will get back to you.
