### ISSUE TITLE
The NVIDIA parser does not provide the right value for StdVideoH264LevelIdc

### ISSUE THREAD

**Issue by dabrain34** [nvpro-samples/vk_video_samples#26]
NVIDIA parser reports in StdVideoH264LevelIdc the extracted value from the bytestream, not the mapped data according the specification.

See https://github.com/Igalia/GstVkVideoParser/pull/33#issuecomment-1348420461

**Comment by dabrain34** [comment]
@zlatinski

**Comment by zlatinski** [comment]
Thank you, [dabrain34](https://github.com/dabrain34), for reporting this issue.
Can you please point me to the content that you are testing against?

**Comment by zlatinski** [comment]
Hi [dabrain34](https://github.com/dabrain34),
This issue should already be addressed with the new version 0.9.7 of the parser. Please check it out.
Thanks!

**Comment by zlatinski** [comment]
Closing this issue since it has already been fixed.
