### ISSUE TITLE
Build's broken and there are runtime errors

### ISSUE THREAD

**Issue by BattleAxeVR** [nvpro-samples/vk_video_samples#29]
Hi, I tried the latest build and the latest code simply doesn't compile due to missing FFMPEG .lib dependencies added in link phase.

Once I fix this manually, then I get various runtime errors on the same mkv test files that worked previously. I'm using the latest beta Nvidia drivers (527.86) and lates FFMPEG build "Latest Auto-Build (2023-01-24 12:34)":

[ffmpeg-master-latest-win64-gpl-shared.zip]
(https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip)

My VulkanSDK is also the latest on the official site, v1.3.236.0. 

The link errors are these (easy to fix manually though):

1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_freep referenced in function "private: virtual __cdecl FFmpegDemuxer::~FFmpegDemuxer(void)" (??1FFmpegDemuxer@@EEAA@XZ)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_packet_alloc referenced in function "private: int __cdecl FFmpegDemuxer::Initialize(int,int,int)" (?Initialize@FFmpegDemuxer@@AEAAHHHH@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_packet_free referenced in function "private: virtual __cdecl FFmpegDemuxer::~FFmpegDemuxer(void)" (??1FFmpegDemuxer@@EEAA@XZ)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_packet_unref referenced in function "public: virtual __int64 __cdecl FFmpegDemuxer::DemuxFrame(unsigned char const * *)" (?DemuxFrame@FFmpegDemuxer@@UEAA_JPEAPEBE@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_bsf_get_by_name referenced in function "private: int __cdecl FFmpegDemuxer::Initialize(int,int,int)" (?Initialize@FFmpegDemuxer@@AEAAHHHH@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_bsf_alloc referenced in function "private: int __cdecl FFmpegDemuxer::Initialize(int,int,int)" (?Initialize@FFmpegDemuxer@@AEAAHHHH@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_bsf_init referenced in function "private: int __cdecl FFmpegDemuxer::Initialize(int,int,int)" (?Initialize@FFmpegDemuxer@@AEAAHHHH@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_bsf_send_packet referenced in function "public: virtual __int64 __cdecl FFmpegDemuxer::DemuxFrame(unsigned char const * *)" (?DemuxFrame@FFmpegDemuxer@@UEAA_JPEAPEBE@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_bsf_receive_packet referenced in function "public: virtual __int64 __cdecl FFmpegDemuxer::DemuxFrame(unsigned char const * *)" (?DemuxFrame@FFmpegDemuxer@@UEAA_JPEAPEBE@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol avcodec_find_decoder referenced in function "private: struct AVFormatContext * __cdecl FFmpegDemuxer::CreateFormatContext(char const *,enum AVCodecID)" (?CreateFormatContext@FFmpegDemuxer@@AEAAPEAUAVFormatContext@@PEBDW4AVCodecID@@@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol avformat_network_init referenced in function "private: struct AVFormatContext * __cdecl FFmpegDemuxer::CreateFormatContext(char const *,enum AVCodecID)" (?CreateFormatContext@FFmpegDemuxer@@AEAAPEAUAVFormatContext@@PEBDW4AVCodecID@@@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol avformat_alloc_context referenced in function "private: struct AVFormatContext * __cdecl FFmpegDemuxer::CreateFormatContext(char const *,enum AVCodecID)" (?CreateFormatContext@FFmpegDemuxer@@AEAAPEAUAVFormatContext@@PEBDW4AVCodecID@@@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol avformat_free_context referenced in function "private: virtual __cdecl FFmpegDemuxer::~FFmpegDemuxer(void)" (??1FFmpegDemuxer@@EEAA@XZ)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol avformat_open_input referenced in function "private: struct AVFormatContext * __cdecl FFmpegDemuxer::CreateFormatContext(char const *,enum AVCodecID)" (?CreateFormatContext@FFmpegDemuxer@@AEAAPEAUAVFormatContext@@PEBDW4AVCodecID@@@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol avformat_find_stream_info referenced in function "private: int __cdecl FFmpegDemuxer::Initialize(int,int,int)" (?Initialize@FFmpegDemuxer@@AEAAHHHH@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_find_best_stream referenced in function "private: int __cdecl FFmpegDemuxer::Initialize(int,int,int)" (?Initialize@FFmpegDemuxer@@AEAAHHHH@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_read_frame referenced in function "public: virtual __int64 __cdecl FFmpegDemuxer::DemuxFrame(unsigned char const * *)" (?DemuxFrame@FFmpegDemuxer@@UEAA_JPEAPEBE@Z)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol av_seek_frame referenced in function "public: virtual void __cdecl FFmpegDemuxer::Rewind(void)" (?Rewind@FFmpegDemuxer@@UEAAXXZ)
1>FFmpegDemuxer.obj : error LNK2019: unresolved external symbol avformat_close_input referenced in function "private: virtual __cdecl FFmpegDemuxer::~FFmpegDemuxer(void)" (??1FFmpegDemuxer@@EEAA@XZ)
1>D:\NV\vk_video_samples\vk_video_decoder\build\demos\Debug\vk-video-dec-test.exe : fatal error LNK1120: 19 unresolved externals

When I try playinb back this HEVC file from the public domain:

https://s3.amazonaws.com/x265.org/video/BigBuckBunny_2000hevc.mp4

I used this command line: vk-video-dec-test.exe -i d:\BigBuckBunny_2000hevc.mp4

![image](https://user-images.githubusercontent.com/11604039/214480810-d653fd06-defd-4605-8e80-e5bcbdc09525.png)

**Comment by zlatinski** [comment]
Hi BattleAxeVR, please upgrade to the latest FFMPEG libraires **and header files** and then do **a clean build** of the decoder. 
This is all FFMPEG related library/header files mismatch.

**Comment by BattleAxeVR** [comment]
I'll try, thanks.

**Comment by BattleAxeVR** [comment]
I just copied the latest ffmpeg from 7 hours ago into the bin dir, rebuilt the VS solution with cmake, and still get this error:

![image](https://user-images.githubusercontent.com/11604039/216466648-1ee04b34-c847-4a8d-b59b-afece77d44bf.png)

**Comment by BattleAxeVR** [comment]
The FFMPEG libs aren't being linked to in the Visual Studio linker section. That's first error, same as before. I synced everything clean and followed all the build instructions to the letter and still get the same errors.

**Comment by BattleAxeVR** [comment]
Same exact runtime errors on the same file as before.

![image](https://user-images.githubusercontent.com/11604039/216470232-5e9f07d4-b92a-426b-8894-66d99b2a1598.png)

**Comment by BattleAxeVR** [comment]
-i d:\BigBuckBunny_2000hevc.mp4

**Comment by BattleAxeVR** [comment]
Ok, sorry, I didn't copy the FFMPEG until after I ran update_sources.bat, I think that might've been the reason for all this. sorry about that

**Comment by BattleAxeVR** [comment]
Actually, the problem I was having is the GStreamer was installed on my machine, to try the other branch that uses it. So cmake was finding the ffmpeg libs from gstreamer instead of the ones I copied to /bin/ffmpeg. Hopefully me writing this helps others avoid the same weird link / runtime errors.
