### ISSUE TITLE
decoder shouldn't create unsupported queries

### ISSUE THREAD

**Issue by airlied** [nvpro-samples/vk_video_samples#44]
status queries are optional:

VkQueueFamilyQueryResultStatusPropertiesKHR.queryResultStatusSupport should be tested before creating or using status queries.

**Comment by zlatinski** [comment]
Sure, my bad, @airlied! I should have NOT created the m_queryPool for platforms that don't support queryResultStatusSupport. I'll fix that.

**Comment by zlatinski** [comment]
Hi @airlied, is the latest version working for you, when it comes to regarding the VkQueueFamilyQueryResultStatusPropertiesKHR.queryResultStatusSupport by the sample?

**Comment by airlied** [comment]
this works now
