### ISSUE TITLE
Please document commandline args to vk-video-dec-test

### ISSUE THREAD

**Issue by Jasper-Bekkers** [nvpro-samples/vk_video_samples#5]
Right now when you don't specify any arguments into the program it just lits a few vulkan extensions and terminates. It would be helpful to list which commandline arguments are required to correctly invoke the program.

**Comment by zlatinski** [comment]
> Right now when you don't specify any arguments into the program it just lits a few vulkan extensions and terminates. It would be helpful to list which commandline arguments are required to correctly invoke the program.

Good suggestion!  Will do that with future releases.

**Comment by zlatinski** [comment]
Fixed with the new app update.
