### ISSUE TITLE
Question: is encode sample up to date with latest encoder specs updated in latest NV VK dev drv?

### ISSUE THREAD

**Issue by oscarbg** [nvpro-samples/vk_video_samples#51]
Hi,
Seeing latest nv vk dev drv release notes:
[VK_KHR_video_encode_queue](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_video_encode_queue.html) version update 8->9
[VK_EXT_video_encode_h264](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_video_encode_h264.html) version update 10->11

As they seem to bring some “big” changes (i.e. incompatible with older revision drivers?) I’m asking if the encode sample here is compatible with latest NV vk dev drv?

in case not, is being updated soon?

just asking before trying to build the encode sample and seeing not working..

thanks..

**Comment by zlatinski** [comment]
Yes, [oscarbg](https://github.com/oscarbg), main branch is now aligned with the latest Vulkan spec.
