### ISSUE TITLE
Request: add h265 support to encode sample..

### ISSUE THREAD

**Issue by oscarbg** [nvpro-samples/vk_video_samples#52]
Hi,

Seems at the end of the project Readme is noted no support yet for h265 encode in this ssmple..

But seeing there is already some “experimental” RADV AMD branches with h265 encode support, and also ffmpeg h265 vulkan encode support patches since very recently.. the question is can we expect similar support from NV “soon enough”: 
namely a vk dev drv and also updates to the encode sample bringing some experimental h265 support..
I say because nvidia latest driver supports even Mesa AV1 decode vk ext..

thanks..

**Comment by oscarbg** [comment]
Thanks!

**Comment by oscarbg** [comment]
Hi,
reopening, forgot that "vk_video_encoder" sample still is h264 only..

**Comment by zlatinski** [comment]
This is already supported by both NV drivers and the sample app.
