### ISSUE TITLE
Request: add av1 support to decode sample..

### ISSUE THREAD

**Issue by oscarbg** [nvpro-samples/vk_video_samples#53]
Hi,

great seeing latest vk dev drv having support for av1 decode Mesa vk ext on Ada..
Can we expect the decode sample to bring av1 support “soon” to test it..
I say also because I made some experiments with a recent (up to 10jul23) ffmpeg from main branch build with vulkan av1 decode support on an Ada GPU with this drv and I’m getting errors, so it’s not working correctly.. still don’t want to provide feedback as may be well a temporal ffmpeg bug being fixed upstream..

Thanks..

**Comment by oscarbg** [comment]
Thanks will try.. interesting is also vp9 support.. maybe next vk dev drv adds vp9 mesa ext..

**Comment by oscarbg** [comment]
two things using that av1 branch:
1) I don't know if due to the my sample av1 file or not but getting:
[ERROR][07:47:48] FFmpeg error: vk_video_samples/vk_video_decoder/libs/NvCodecUtils/FFmpegDemuxer.cpp 144 av_bsf_get_by_name(): 226 failed
2)really noticing won't work as sample uses "VK_STD_vulkan_video_codec_av1_decode" revision 0.9 not the MESA ext..

**Comment by zlatinski** [comment]
Please note that the [av1-vp9-wip-01](https://github.com/nvpro-samples/vk_video_samples/tree/av1-vp9-wip-01) branch is an internal experimental branch. Please do  not use it. We are working on releasing AV1 specification along with drivers and sample code soon.

**Comment by zlatinski** [comment]
[oscarbg](https://github.com/oscarbg), [av1-vp9-wip-01](https://github.com/nvpro-samples/vk_video_samples/tree/av1-vp9-wip-01) branch is almost ready for us to start merging it to main.

**Comment by oscarbg** [comment]
thanks for info! you mean the "video-decode-av1-beta" branch right? as the other is not existant..
also can you clarify if similarly, main branch is better right now for testing encode than "video-encode-h264-265-alpha"
seems main branch has been receiving some encoding commits also..

**Comment by zlatinski** [comment]
Yes, video-decode-av1-beta, sorry for the confusion!
 
> also can you clarify if similarly, main branch is better right now for testing encode than "video-encode-h264-265-alpha"
seems main branch has been receiving some encoding commits also..

Yes, I have just deleted video-encode-h264-265-alpha. However, the encoder still has some issues with the DPB management that we are working on addressing.
