### ISSUE TITLE
Can't built encode sample with latest headers

### ISSUE THREAD

**Issue by SaschaWillems** [nvpro-samples/vk_video_samples#54]
I've been trying to build the encode sample with the latest header, but `VkVideoEncodeH264VclFrameInfoEXT` seems to be undefined. I also can't find that identifier in the latest Vulkan headers.

Any clues on how to compile the encode sample with the latest Vulkan headers?

**Comment by zlatinski** [comment]
Hi Sascha,
We are in the process of updating the Vulkan Video API and so the sample app. We are also in the process of adding more advanced encoding modes and codecs. The current app only encodes AVC I-frames.
Most likely the updated app will be ready by end of September.

**Comment by SaschaWillems** [comment]
Thanks for the update. Will wait and test again after the update :)

**Comment by zlatinski** [comment]
[SaschaWillems](https://github.com/SaschaWillems), Please check the code at the ToT of main.
Also, [SaschaWillems](https://github.com/SaschaWillems), for your samples, can you also please check the code from Bernhard from the University of Viena at https://github.com/clemy/vulkan-video-encode-simple? This code looks more appropriate (simple) for use with samples.
