### ISSUE TITLE
Linux Nvidia driver version for video encode?

### ISSUE THREAD

**Issue by brianpaul** [nvpro-samples/vk_video_samples#63]
Hi, it wanted to try the video encoder sample.  I have the 535.43.22 beta driver which supports the video encode/decode extensions.  The video decode sample works but the video encode sample fails with an VK_ERROR_INCOMPATIBLE_DRIVER error.

I also tried to install the 515.49.24 driver linked to by the BUILD.md file but I can't install it on Ubuntu 22.04.  The kernel module fails to build with the 6.5.0 kernel.

Is there another beta driver that will work, or what kernel do I need to for the 515.49.24 driver?

Thanks.

**Comment by zlatinski** [comment]
Hi @brianpaul,

Can you please try the https://github.com/nvpro-samples/vk_video_samples/tree/video-encode-h264-265-alpha branch. This code base will be the one merged to main after fixing some of the outstanding issues with encoding h.264 and h.265 content. So, please keep in  mind that this branch is still a WIP preview, but at least you should be able to create video encode-enabled  devices successfully and encode content. Please refer to the list of issues in the Readme that we are working on addressing. Please also note that there are validation layer issues that need addressing. 
As always, we also welcome community fixes and contributions.

**Comment by zlatinski** [comment]
[brianpaul](https://github.com/brianpaul), please check the latest ToT code at main.
