### ISSUE TITLE
Where is EncPicParams::refPicList initialised?

### ISSUE THREAD

**Issue by friesofdoom** [nvpro-samples/vk_video_samples#65]
https://github.com/nvpro-samples/vk_video_samples/blob/9840c6416353d6b9359407711544e85af6527cfb/vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.h#L303

Should it get a call to GetReferenceFrameResourcesByIndex possibly?

It gets used here, but never initialized properly.
https://github.com/nvpro-samples/vk_video_samples/blob/9840c6416353d6b9359407711544e85af6527cfb/vk_video_encoder/libs/VkVideoEncoder/VkVideoEncoder.cpp#L890

Is the code in Main in a stable state? It looks like it might not be - semi refactored?

Thanks!

**Comment by zlatinski** [comment]
@friesofdoom, the encoder portion of the sample in main is outdated and deprecated.  Please use the https://github.com/nvpro-samples/vk_video_samples/tree/video-encode-h264-265-alpha WIP branch for your evaluation.

**Comment by zlatinski** [comment]
[friesofdoom](https://github.com/friesofdoom), please check the latest ToT code at main.
