### ISSUE TITLE
AV1 Decode: videoSessionParametersTemplate should be NULL

### ISSUE THREAD

**Issue by lolzballs** [nvpro-samples/vk_video_samples#68]
If multiple sequence headers are present in the AV1 stream, the AV1 decoder will try to create a new `VkVideoSessionParametersKHR` with a videoSessionParametersTemplate set to the old one. [VUID-VkVideoSessionParametersCreateInfoKHR-videoSession-09258](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkVideoSessionParametersCreateInfoKHR.html#VUID-VkVideoSessionParametersCreateInfoKHR-videoSession-09258) requires that `VkVideoSessionParametersCreateInfoKHR::videoSessionParametersTemplate` is NULL for AV1 decode parameters.

On AMD's beta driver, this causes the `vkCreateVideoSessionParametersKHR` to return an error.

**Comment by zlatinski** [comment]
Thank you, [lolzballs](https://github.com/lolzballs)! We'll fix that issue.

**Comment by zlatinski** [comment]
This is fixed now with 63c1ac2 at the ToT of https://github.com/nvpro-samples/vk_video_samples/tree/video-decode-av1-beta
