### ISSUE TITLE
Build failure with "Error: Unsupported option --v-lvl-root" on macos

### ISSUE THREAD

**Issue by ilongshan** [nvpro-samples/vk_video_samples#7]
Build failure with "Error: Unsupported option --v-lvl-root" on macos because "vk_video_decoder/external/MoltenVK/fetchDependencies" doesn't have "--v-lvl-root" option.

**Comment by zlatinski** [comment]
> Build failure with "Error: Unsupported option --v-lvl-root" on macos because "vk_video_decoder/external/MoltenVK/fetchDependencies" doesn't have "--v-lvl-root" option.

This application does not support MACOS - only Windows 10 and Linux are currently supported.
