### ISSUE TITLE
decoder should respect more vulkan capability limits

### ISSUE THREAD

**Issue by airlied** [nvpro-samples/vk_video_samples#9]
It looks like the player reads the  VkVideoCapabilitiesKHR struct, but doesn't seem to use them anywhere.

I think it should probably be making sure alignments for bs and video picture granularity are properly support.

**Comment by zlatinski** [comment]
> It looks like the player reads the VkVideoCapabilitiesKHR struct, but doesn't seem to use them anywhere.
> 
> I think it should probably be making sure alignments for bs and video picture granularity are properly support.

I agree with you, Dave. We should consider the fields from VkVideoCapabilitiesKHR when dealing with the bitstream and the images. We'll do that as part of the future sample app releases.

**Comment by zlatinski** [comment]
Done as part of the last release.
