### ISSUE TITLE
Android platform is not supported

### ISSUE THREAD

**Issue by mandagod** [nvpro-samples/vk_video_samples#94]
Android platform is not supported, is there any support later?

**Comment by dabrain34** [comment]
Android platform does not support Vulkan Video extensions

**Comment by BattleAxeVR** [comment]
I would also love for there to be Vulkan Video support on Android, so I can write an end-to-end VV-based transport layer for a PC VR streaming app, get rid of needing middleware libraries like GStreamer or CloudXR, which have several limitations / gotchas.

**Comment by zlatinski** [comment]
Unfortunately, the allowed Android extensions are controlled by Google, and the company currently does not allow Vulkan video extensions to be exposed. Please contact Gogole to express your interest in that for them to allow it.
